coverage:
  range: 50..100
  round: down
  precision: 2
  ignore:
  - Tests/*
  status:
    project:
      default: false
      framework:
        target: auto
        paths: "Sources/"
    patch: off
codecov:
  bot: "codecov-io"
  ci:
    - "travis.org"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 0
    wait_for_ci: no
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post] 
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no