coverage:
  range: 70..100
  round: down
  precision: 2
  ignore:
  - Tests/*
  status:
    project:
      default: false
      framework:
        target: auto
        paths: "Sources/"
    patch: off