gemfile: Gemfile

concurrency: '1'

PostCheckout:
  CustomScript:
    enabled: true
    command: ["./bin/post-checkout.sh"]

PreCommit:
  BundleCheck:
    enabled: true

  CustomScript:
    enabled: true
    command: ["./bin/pre-commit.sh"]