language: swift
osx_image: xcode10.3

addons:
  homebrew:
    brewfile: true

script:
- set -o pipefail
- swift --version
- rake
- rake test
- bundle exec fastlane pass_tests
- bundle exec pod repo update
- bundle exec pod lib lint --allow-warnings
- bundle exec danger