language: swift
osx_image: xcode11.3
if: tag is blank

cache:
  bundler: true
  cocoapods: true

addons:
  homebrew:
    brewfile: true

script:
- set -o pipefail
- swift --version
- rake
- rake test
- bundle exec fastlane pass_tests
- bundle exec pod repo update
- bundle exec pod lib lint --allow-warnings --fail-fast --subspec="Core"
- bundle exec pod lib lint --allow-warnings --fail-fast --subspec="Log"
- bundle exec pod lib lint --allow-warnings --fail-fast --subspec="Test"
- bundle exec danger
